version: '3.9'

services:
  db:
    image: postgres:14
    container_name: ft_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ft_news
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ft_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ft_news
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head && python app/scraper/ft_scraper.py"

volumes:
  postgres_data:
